#!/usr/bin/env python3
"""Build the static code index and a project-only ZIP from the same source files."""

import argparse
import hashlib
import io
import json
from pathlib import Path
import zipfile

ROOT = Path(__file__).resolve().parents[1]
PROJECTS = ROOT / "projects"


def artifacts(project):
    sources = sorted((project / "src").rglob("*.java"))
    readable = [project / "README.md"] + sources
    # An allowlist keeps IDE session files, bytecode and site assets out of the ZIP.
    portable = [project / ".gitignore", *project.glob("*.iml")]
    portable += [project / ".idea" / name for name in (".gitignore", "misc.xml", "modules.xml")]
    members = sorted(set(readable + [path for path in portable if path.is_file()]))
    for path in members:
        if path.is_symlink() or project.resolve() not in path.resolve().parents:
            raise ValueError(f"Not a regular project file: {path}")
    files = []
    for path in readable:
        content = path.read_bytes()
        files.append({"path": path.relative_to(project).as_posix(),
                      "language": "Java" if path.suffix == ".java" else "Markdown",
                      "content": content.decode("utf-8"), "bytes": len(content)})
    archive = io.BytesIO()
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as bundle:
        for path in members:
            name = f"{project.name}/{path.relative_to(project).as_posix()}"
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            bundle.writestr(info, path.read_bytes())
    zipped = archive.getvalue()
    data = {"id": project.name, "files": files, "sourceCount": len(sources),
            "archive": f"{project.name}.zip", "archiveBytes": len(zipped),
            "revision": hashlib.sha256(zipped).hexdigest()[:12]}
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    # This is a separate classic script, so opening the viewer via file:// also works.
    payload = payload.replace("<", "\\u003c").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    script = f"// Generated by scripts/package_projects.py; edit the source files instead.\nwindow.COURSE_PROJECT = {payload};\n"
    return {project / data["archive"]: zipped, project / "project-data.js": script.encode("utf-8")}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", nargs="?", help="Folder name inside projects/; omit to build all projects")
    parser.add_argument("--check", action="store_true", help="Report stale artifacts without writing files")
    args = parser.parse_args()
    if args.project and (Path(args.project).name != args.project or args.project in (".", "..")):
        parser.error("Use a project folder name, not a path")
    projects = [PROJECTS / args.project] if args.project else sorted(p for p in PROJECTS.iterdir() if (p / "src").is_dir())
    stale = []
    for project in projects:
        if not (project / "src").is_dir() or not (project / "README.md").is_file():
            parser.error(f"{project.name} needs src/ and README.md")
        for path, content in artifacts(project).items():
            if args.check:
                if not path.exists() or path.read_bytes() != content:
                    stale.append(str(path.relative_to(ROOT)))
            else:
                path.write_bytes(content)
        print(f"{project.name}: {'checked' if args.check else 'packaged'}")
    if stale:
        parser.exit(1, "Regenerate stale artifacts: " + ", ".join(stale) + "\n")


if __name__ == "__main__":
    main()
